'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const {spawnSync} = require('child_process');

const root = path.resolve(__dirname, '..', '..');
const modulesDir = path.join(root, 'scripts', 'modules');
const scriptsDir = path.join(root, 'scripts');
const buildTool = fs.readFileSync(path.join(root, 'tools', 'build-shared-modules.mjs'), 'utf8');

const controllerMappings = [
  ['archive-controller.mjs', 'archive.js'],
  ['literature-controller.mjs', 'literature.js'],
  ['vision-board-controller.mjs', 'vision-board.js'],
  ['universe-controller.mjs', 'universes.js'],
  ['connections-controller.mjs', 'connections.js'],
  ['bridges-controller.mjs', 'bridges.js'],
  ['connections-map-controller.mjs', 'connections-map.js'],
  ['bridges-map-controller.mjs', 'bridges-map.js'],
  ['data-portability-controller.mjs', 'export-import.js'],
  ['settings-controller.mjs', 'modals-settings.js'],
  ['generation-controller.mjs', 'generation.js'],
  ['folder-storage-controller.mjs', 'folder-storage.js'],
  ['storage-facade.mjs', 'storage.js']
];

const infrastructureMappings = [
  ['controller-service-registry.mjs', 'wormholes-controller-services.js'],
  ['tagging-helpers.mjs', 'wormholes-tagging-helpers.js'],
  ['map-presentation-helpers.mjs', 'wormholes-map-presentation-helpers.js'],
  ['app-data-validation.mjs', 'wormholes-app-data-validation.js'],
  ['document-zip-helpers.mjs', 'wormholes-document-zip-helpers.js'],
  ['app-core.mjs', 'wormholes-app.js'],
  ['bootstrap.mjs', 'bootstrap.js'],
  ['global-search.mjs', 'global-search.js'],
  ['single-tab.mjs', 'single-tab.js'],
  ['accessibility.mjs', 'wormholes-accessibility.js'],
  ['activity-log.mjs', 'wormholes-activity-log.js'],
  ['backup-status.mjs', 'wormholes-backup-status.js'],
  ['copy-to-universe.mjs', 'wormholes-copy-to-universe.js'],
  ['dialog-keyboard.mjs', 'wormholes-dialog-keyboard.js'],
  ['dialogs.mjs', 'wormholes-dialogs.js'],
  ['duplicate-creations.mjs', 'wormholes-duplicate-creations.js'],
  ['error-reporting.mjs', 'wormholes-error-reporting.js'],
  ['escape-policy.mjs', 'wormholes-escape.js'],
  ['focus.mjs', 'wormholes-focus.js'],
  ['indexeddb-recovery.mjs', 'wormholes-indexeddb-recovery.js'],
  ['large-data-store.mjs', 'wormholes-large-data-store.js'],
  ['map-search.mjs', 'wormholes-map-search.js'],
  ['persisted-schema.mjs', 'wormholes-persisted-schema.js'],
  ['search-index.mjs', 'wormholes-search-index.js'],
  ['recovery-snapshots.mjs', 'wormholes-snapshots.js'],
  ['startup-coordinator.mjs', 'wormholes-startup.js'],
  ['storage-dashboard.mjs', 'wormholes-storage-dashboard.js'],
  ['storage-recovery.mjs', 'wormholes-storage-recovery.js'],
  ['undo.mjs', 'wormholes-undo.js'],
  ['write-ahead-journal.mjs', 'wormholes-write-ahead-journal.js']
];

for(const [moduleName, legacyName] of [...controllerMappings, ...infrastructureMappings]){
  const modulePath = path.join(modulesDir, moduleName);
  const legacyPath = path.join(scriptsDir, legacyName);
  assert.ok(fs.existsSync(modulePath), `${moduleName} should exist as canonical module source`);
  assert.ok(fs.existsSync(legacyPath), `${legacyName} should exist as direct-file adapter`);
  const moduleSource = fs.readFileSync(modulePath, 'utf8');
  const legacySource = fs.readFileSync(legacyPath, 'utf8');
  assert.match(buildTool, new RegExp(moduleName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `${moduleName} should be generated by the module build tool`);
  assert.ok(/export\s*(?:\{|const|function|class)/.test(moduleSource), `${moduleName} should contain ES-module export syntax`);
  assert.ok(legacySource.startsWith(`/* GENERATED from scripts/modules/${moduleName}.`), `${legacyName} should be generated from ${moduleName}`);
}

for(const [moduleName] of controllerMappings.filter(([name]) => name.endsWith('-controller.mjs'))){
  const source = fs.readFileSync(path.join(modulesDir, moduleName), 'utf8');
  assert.match(source, /from "\.\/controller-service-registry\.mjs"/, `${moduleName} should import the controller-service contract`);
  assert.match(source, /registerControllerServices\(/, `${moduleName} should publish its controller service surface`);
}

const manifestSource = fs.readFileSync(path.join(modulesDir, 'runtime-manifest.mjs'), 'utf8');
for(const [, legacyName] of controllerMappings.filter(([name]) => name.endsWith('-controller.mjs'))){
  assert.ok(!manifestSource.includes(`"scripts/${legacyName}"`), `${legacyName} should not remain a served-runtime classic adapter`);
}
assert.match(manifestSource, /servedNativeControllerModulesBeforeAppCore/, 'served runtime should expose its native controller module list');

const moduleFiles = fs.readdirSync(modulesDir).filter(name => name.endsWith('.mjs'));
assert.ok(moduleFiles.length >= 72, `expected at least 72 canonical ES modules, found ${moduleFiles.length}`);

const handAuthoredClassic = fs.readdirSync(scriptsDir)
  .filter(name => name.endsWith('.js'))
  .filter(name => !fs.readFileSync(path.join(scriptsDir, name), 'utf8').startsWith('/* GENERATED from '));
assert.deepStrictEqual(handAuthoredClassic, [], 'all classic runtime JavaScript should be generated compatibility output after Beta 253');

const check = spawnSync(process.execPath, ['tools/build-shared-modules.mjs', '--check'], {cwd:root, encoding:'utf8'});
assert.strictEqual(check.status, 0, `${check.stdout || ''}${check.stderr || ''}`);

console.log('ES module controller/infrastructure source tests passed.');
